# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the makefile checks the same files as pre-commit
#   * MyPy gets all dependencies as additional dependencies
repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
      - id: black
        args:
            - --diff
            - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        language: python
        language_version: python3.8
        files: ^(main|bot/.*)\.py$
        args:
        - --rcfile=setup.cfg
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        language: python
        language_version: python3.8
        additional_dependencies:
            - python-telegram-bot>=13.3,<14.0
            - git+https://github.com/python-telegram-bot/ptbcontrib.git@5eda3817f8a4ee196dfa37efd5775ed00c7b047c
            - pytz
            - rapidfuzz==1.1.1
        files: ^(main|bot/.*)\.py$